baseURL = 'https://www.oludo.com.br'
languageCode = 'pt-br'
title = 'Oludo'
theme = 'oludo'
enableRobotsTXT = true

[params]
Pixel = "337191138296175"
GTags = ['G-WTWXJMGSBH']
FBDomainVerification = "feescgj7bfjhknnmvsd9jiskp4h7bw"
